name: Build Test Deploy on Windows

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  issues:
    types: [opened, edited]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Print message
        run: echo "Build job running on Windows"

  test:
    needs: build
    runs-on: windows-latest
    steps:
      - name: Run tests
        run: echo "Running tests..."

  deploy:
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: windows-latest
    steps:
      - name: Deploy code
        run: echo "Deploying to production..."
