name: First GitHub Action

on:
  push:
    branches:
      - main  # Ensure this is set to the correct branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run a greeting
        run: echo "Hello, GitHub Actions is working!"
