name: Issue Automation

on:
  issues:
    types: [opened, edited, labeled, closed, reopened]

jobs:
  respond-to-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Print issue info
        run: |
          echo "Issue #${{ github.event.issue.number }}"
          echo "Action: ${{ github.event.action }}"
          echo "Title: ${{ github.event.issue.title }}"
