name: PR Labeled Event

on:
  pull_request:
    types:
      - labeled

jobs:
  label-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Print PR label
        run: echo "A label has been added to the PR."
