name: On Push Event

on: 
 push:
   branches:
     - main
 

jobs:
  build:
     runs-on: ubuntu-latest
steps:
     - name: Checout code
       uses: actions/checkout@v3

     - name: Run echo command
       run: echo "Push event triggered"
     
       run: echo "this workflow runs on any push event"
     
