name: On Version Tag Push

on:
  push:
    tags:
      - 'v*'


jobs:
    tag-job:
     runs-on: ubuntu-latest

     steps:
      - name: Print tag
        run: echo "New release tag pushed:${{github.ref}}"
    
    
